# Generated by Django 4.2 on 2023-07-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breand',
            new_name='Brand',
        ),
    ]
