# Generated by Django 4.2 on 2024-02-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_buyer_alter_product_pic1_alter_product_pic4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
